pathToTarget: Images/target.png
pathToStart: Images/start.png
pretendersInIteration: 100
survivingRateInChange: 5
changesPerIteration: 5
iterationsCount: 10000
sameScaleForBothAxis: false
minScale: 0.10000000149011612
maxScale: 1
minRotation: 0.10000000149011612
maxRotation: 1
maxOriginChange: 40
maxScaleChange: 0.05000000074505806
maxRotationChange: 10
